---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#


# main tasks file for ipst.jdk8

- debug:
    var="{{ item }}"
  when: "0==0"
  with_items:
    - jdk8_archivename
    - jdk8_url
    - jdk8_dest_path
    - jdk8_prefix

- name: check if already installed
  stat: path={{ jdk8_prefix }}
  register: jdk8_dir
  changed_when: jdk8_dir.stat.exists == False

- include: install.yml
  when: jdk8_dir.stat.exists == False