---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#


# main tasks file for ipst.wildfly

- name: check if already installed
  stat: path={{ wildfly_prefix }}
  register: wildfly_dir
  changed_when: wildfly_dir.stat.exists == False

- include: install.yml
  when: wildfly_dir.stat.exists == False
